language: android
dist: trusty
android:
  components:
  - tools
  - build-tools-29.0.3
  - android-29
  - platform-tools
  licenses:
    - '.+'

sudo: required

jdk:
  - oraclejdk8

install: true

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease --stacktrace